import { OrganizationType } from "../enum/OrganizationTypeenum";

export const ORGANIZATION_FORM_DEFAULTS = {
  id: "",
  organizationCode: "",
  organizationName: "",
  organizationType: OrganizationType.School,
  affiliationBoard: "",
  logoUrl: "",
  establishedYear: 2000,
  registrationNumber: "",
  panTinTaxId: "",
  address1: "",
  address2: "",
  city: "",
  state: "",
  country: "",
  postalCode: "",
  landmark: "",
  latitude: undefined,
  longitude: undefined,
  contactNumber: "",
  alternateContactNumber: "",
  email: "",
  websiteUrl: "",
  headOfOrganization: "",
  academicYearStart: "",
  academicYearEnd: "",
  timezone: "",
  currency: "",
  locale: "",
  isActive: true,
} as const;
