export const STUDENTENROLLMENT_DEFAULTS = {
  studentdto: {
    id: undefined,
    organizationId: '',
    branchId: '',
    academicYearId: '',
    admissionNumber: '',
    admissionDate: '',
    studentCategory: '',
    stream: '',
    medium: '',
    transferCertificateNo: '',
    studentPhotoUrl: '',
    studentPhoto: null,
    studentBarcode: '',
    studentSignature: null,
    enquiryNumber: '',
    rollNumber: '',
    name: '',
    dateOfBirth: '',
    gender: '',
    email: '',
    mobile: '',
    bloodGroup: '',
    identificationInfo: {
      aadharNumber: '',
      panNumber: '',
      passportNumber: '',
      caste: '',
      religion: '',
      nationality: '',
      motherTongue: '',
    },
    address: {
      firstName: '',
      lastName: '',
      emailAddress: '',
      addressLine: '',
      country: '',
      state: '',
      zipCode: '',
    },
    bankDetails: {
      bankAccountNumber: '',
      bankIFSCCode: '',
      bankName: '',
      bankBranch: '',
      accountHolderName: '',
      accountType: '',
    },
    emergencyContact: {
      name: '',
      relation: '',
      contactNumber: '',
      address: '',
      AadharNo: '',
    },
    healthRecord: {
      bloodGroup: '',
      height: '',
      weight: '',
      allergies: '',
      medicalConditions: '',
      emergencyContact: '',
    },
    hostelDetails: {
      hostelName: '',
      roomNumber: '',
      bedNumber: '',
      wardenName: '',
      wardenContact: '',
    },
    previousSchoolDetails: {
      schoolName: '',
      schoolBoard: '',
      percentage: '',
    },
    transportDetails: {
      transportMode: '',
      routeNumber: '',
      pickupPoint: '',
      dropPoint: '',
      driverName: '',
      driverContact: '',
    },
     
    studentStatus: '',
    classEnrollments: [],
    extraCurriculars: [],
    academicHistories: [],
    familyMembers: [],
  },
  studentPhotoBase64: null,
  studentSignatureBase64: null,
};
